import { AcademicTitle } from './models/academic-title';

export const academicTraining: AcademicTitle[] = [
  {
    full_academic_title: 'ASSOCIATE DEGREE IN WEB DEVELOPMENT',
    academic_title: 'ASSOCIATE DEGREE',
    specialist: 'WEB DEVELOPMENT',
    acronym: 'WD',
    start_year: 2018,
    end_year: 2020,
    location: 'Valencia (Spain)',
  },
  {
    full_academic_title: 'ASSOCIATE DEGREE IN NETWORK SYSTEM ADMINISTRATION',
    academic_title: 'ASSOCIATE DEGREE',
    specialist: 'NETWORK SYSTEM ADMINISTRATION',
    acronym: 'NSA',
    start_year: 2015,
    end_year: 2017,
    location: 'Valencia (Spain)',
  },
  {
    full_academic_title: 'BACHELOR OF TECHNOLOGY SCIENCES',
    academic_title: 'BACHELOR',
    specialist: 'SCIENCES',
    acronym: 'BACHELOR',
    start_year: 2012,
    end_year: 2015,
    location: 'Torrent (Valencia, Spain)',
  },
];

export const courses: AcademicTitle[] = [
  {
    full_academic_title: '',
    academic_title: 'Good practices on Angular',
    specialist: '',
    acronym: '',
    start_year: 2019,
    end_year: 2019,
    location: 'OpenWebinars',
    url_certificate: 'https://openwebinars.net/certificado/9xddORNx',
    isOnline: true,
  },
  {
    full_academic_title: '',
    academic_title: 'Clean Code',
    specialist: '',
    acronym: '',
    start_year: 2019,
    end_year: 2019,
    location: 'OpenWebinars',
    url_certificate: 'https://openwebinars.net/certificado/0vRQDkKV',
    isOnline: true,
  },
  {
    full_academic_title: '',
    academic_title: 'Refactoring and Clean Code techniques',
    specialist: '',
    acronym: '',
    start_year: 2019,
    end_year: 2019,
    location: 'OpenWebinars',
    url_certificate: 'https://openwebinars.net/certificado/1VZL4A0x',
    isOnline: true,
  },
  {
    full_academic_title: '',
    academic_title: 'Node.js and Express',
    specialist: '',
    acronym: '',
    start_year: 2019,
    end_year: 2019,
    location: 'OpenWebinars',
    url_certificate: 'https://openwebinars.net/certificado/0oYDXABx',
    isOnline: true,
  },
  {
    full_academic_title: '',
    academic_title: 'Kubernetes by a DevOps Guru',
    specialist: '',
    acronym: '',
    start_year: 2019,
    end_year: 2019,
    location: 'Udemy',
    url_certificate: 'https://www.udemy.com/certificate/UC-IEAH1FKV/',
    isOnline: true,
  },
  {
    full_academic_title: '',
    academic_title: 'Project management Software with Git and GitHub',
    specialist: '',
    acronym: '',
    start_year: 2018,
    end_year: 2018,
    location: 'Miríadax',
    url_certificate: 'https://certificados.miriadax.net/4c5btihg',
    isOnline: true,
  },
];
