name: Deploy ssr on production server

on: 
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.11.x'
    - name: Install dependencies
      run: npm install
    - name: Run linter
      run: npm run lint
    - name: Build ssr for testing
      run: npm run build:ssr:dev
    - name: Run all test
      uses: cypress-io/github-action@v2
      with:
        start: npm run serve:ssr
        wait-on: 'http://localhost:4200'
        command: npm run test:all
    - name: Build ssr for production
      run: npm run build:ssr:prod
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/my-web-front/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_TARGET_FOLDER }}
    - name: Reload pm2 server
      uses: fifsky/ssh-action@master
      with:
        command: |
          pm2 restart 0
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY}}