name: Deploy ssr to server

on: 
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.11.x'
    - name: Run linter
      run: npm run lint
    - name: Install dependencies
      run: npm install
    - name: Run app to test
      run: npm run start
    - name: Run e2e test
      run: npm run e2e
    - name: Build for ssr
      run: npm run build:ssr
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/my-web-front/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_TARGET_FOLDER }}